services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    ports:
      - "64110:8000"
    environment:
      - DEBUG=false
      - HOST=0.0.0.0
      - PORT=8000
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/api/health', timeout=10)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s