version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      # Mount source code for hot reload during development
      - .:/app
      # Use named volume for Python cache to avoid permission issues
      - python_cache:/home/appuser/.cache
    environment:
      - DEBUG=true
      - HOST=0.0.0.0
      - PORT=8000
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/api/health', timeout=10)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    # Override the default command to enable reload for development
    command: ["python", "-c", "import uvicorn; uvicorn.run('app.main:app', host='0.0.0.0', port=8000, reload=True)"]
    networks:
      - freedium-dev

networks:
  freedium-dev:
    driver: bridge

volumes:
  python_cache: